import streamlit as st
import asyncio
import os
import sys

# Ensure src is in pythonpath
sys.path.append(os.path.abspath("src"))

from mnemosyne.poc.generator import BundleGenerator

st.set_page_config(page_title="Mnemosyne POC", layout="wide")

def init_state():
    if "step" not in st.session_state:
        st.session_state.step = 1
    if "bundle_data" not in st.session_state:
        st.session_state.bundle_data = None
    if "generator" not in st.session_state:
        st.session_state.generator = BundleGenerator()

async def generate_bundle_action(company, industry, description, goal):
    with st.spinner("consulting Mnemosyne core logic..."):
        data = await st.session_state.generator.generate_monthly_bundle(
            company_name=company,
            industry=industry,
            description=description,
            goal=goal,
            num_posts=8
        )
        st.session_state.bundle_data = data
        st.session_state.step = 2

def main():
    init_state()
    
    st.title("Mnemosyne: Research POC")
    st.markdown("Automated Social Strategy & Content Generation")
    
    # --- SCREEN 1: SETUP ---
    if st.session_state.step == 1:
        st.header("Company Setup")
        
        col1, col2 = st.columns(2)
        with col1:
            company = st.text_input("Company Name", value="Simbli")
            industry = st.text_input("Industry", value="SaaS / AI")
        with col2:
            goal = st.selectbox("Primary Goal", ["Brand Awareness", "Hiring", "Product Launch"])
            description = st.text_area("Description", value="Simbli organizes the world's strategic intelligence.")
            
        if st.button("Generate Monthly Strategy"):
            asyncio.run(generate_bundle_action(company, industry, description, goal))
            st.rerun()

    # --- SCREEN 2 & 3: STRATEGY & BUNDLE ---
    elif st.session_state.step >= 2:
        data = st.session_state.bundle_data
        
        # SCREEN 2: SNAPSHOT
        st.divider()
        st.subheader("Strategy Snapshot")
        colA, colB = st.columns([2, 1])
        with colA:
            st.info(f"**Monthly Focus:** {data['strategy_snapshot']}")
        with colB:
            # Show assumption
            assumptions = data['assumptions']
            if assumptions:
                st.warning(f"**Key Bet:** {assumptions[0].statement}")
        
        # SCREEN 3: BUNDLE GRID
        st.divider()
        st.subheader("Scheduled Content Bundle")
        
        posts = data['posts']
        
        # Grid layout
        cols = st.columns(4)
        for i, post in enumerate(posts):
            with cols[i % 4]:
                st.caption(f"Date: {post['date']}")
                
                # Image Display
                if post['image_artifact']:
                    # In a real app we'd load the URL/path
                    # Here we load the local file generated by our renderer
                    try:
                        st.image(post['image_artifact'].file_path, use_container_width=True)
                    except Exception:
                        st.error("Image missing")
                        
                    st.caption(f"Intent: {post['visual_intent'].visual_style}, {post['visual_intent'].human_presence}")
                
                st.text_area("Caption", value=post['content'], height=150, key=f"post_{i}")
                st.divider()

        # SCREEN 4: EXPORT
        st.divider()
        st.subheader("Next Steps")
        c1, c2, c3 = st.columns(3)
        with c1:
            st.button("Download Captions (CSV)")
        with c2:
            st.button("Download Asset Bundle (ZIP)")
        with c3:
            if st.button("Reset"):
                st.session_state.step = 1
                st.session_state.bundle_data = None
                st.rerun()

if __name__ == "__main__":
    main()
